# Generated by Django 4.0.3 on 2022-07-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmCajasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_manual', models.CharField(blank=True, default='', max_length=50)),
                ('manual', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.RenameField(
            model_name='registroquebranto',
            old_name='Nombre_Cajera',
            new_name='Nombre_cajera',
        ),
        migrations.RenameField(
            model_name='registroquebranto',
            old_name='Num_Cajera',
            new_name='Num_cajera',
        ),
    ]
