# Generated by Django 4.0.7 on 2022-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmCajasApp', '0002_manuales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('Fecha_registro', models.DateField(auto_now=True, null=True)),
                ('sucursal', models.IntegerField()),
                ('fecha_error', models.DateField()),
                ('num_cajera', models.IntegerField()),
                ('num_boleta', models.IntegerField()),
                ('grupo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='registroquebranto',
            name='Fecha_registro',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
