# Generated by Django 4.0.5 on 2022-08-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmCajasApp', '0004_alter_errores_comentario_alter_errores_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroquebranto',
            old_name='Fecha_registro',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='registroquebranto',
            name='Comentario',
        ),
        migrations.RemoveField(
            model_name='registroquebranto',
            name='Faltante',
        ),
        migrations.RemoveField(
            model_name='registroquebranto',
            name='Fecha_faltante',
        ),
        migrations.RemoveField(
            model_name='registroquebranto',
            name='Nombre_cajera',
        ),
        migrations.RemoveField(
            model_name='registroquebranto',
            name='Num_cajera',
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='fecha_faltante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='importe_faltante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='nombre_cajera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='num_boleta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='num_cajera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registroquebranto',
            name='sucursal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
