# Generated by Django 4.0.5 on 2022-08-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmCajasApp', '0006_prespromotora_presretop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresCreditosD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('num_orden', models.IntegerField()),
                ('fecha_orden', models.DateField()),
                ('importe', models.IntegerField()),
                ('plan', models.CharField(max_length=5)),
            ],
        ),
    ]
