# Generated by Django 4.0.5 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuales',
            name='nombre_manual',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
