# Generated by Django 4.0.3 on 2022-07-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FuncionariosApp', '0001_initial'),
        ('CajasApp', '0003_retiracliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiracliente',
            name='sucursal_retiro',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('51', '51'), ('52', '52')]),
        ),
        migrations.CreateModel(
            name='ChequeUniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal_cheque', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('51', '51'), ('52', '52')])),
                ('articulo_cheque', models.CharField(max_length=17)),
                ('comentario_cheque', models.CharField(max_length=200)),
                ('ci_fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncionariosApp.funcionarios')),
            ],
        ),
    ]
