# Generated by Django 4.0.3 on 2022-07-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0004_alter_retiracliente_sucursal_retiro_chequeuniforme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequeuniforme',
            old_name='ci_fun',
            new_name='cedula_funcionario',
        ),
    ]
