# Generated by Django 4.0.3 on 2022-07-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0005_rename_ci_fun_chequeuniforme_cedula_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeuniforme',
            name='cedula_funcionario',
            field=models.IntegerField(),
        ),
    ]
