# Generated by Django 4.0.3 on 2022-07-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0008_alter_chequeuniforme_cedula_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manuales',
        ),
    ]
