# Generated by Django 4.0.5 on 2022-08-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0011_delete_docimprimir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChequeUniforme',
        ),
    ]
