# Generated by Django 4.0.5 on 2022-08-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0012_delete_chequeuniforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeCreditelCdelaCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('empresa_cliente', models.CharField(max_length=50)),
                ('importe_cliente', models.IntegerField()),
                ('fpago_cliente', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario', models.CharField(max_length=20)),
                ('num_vta', models.IntegerField()),
                ('num_dev', models.IntegerField()),
                ('imp_facturado', models.IntegerField()),
                ('num_seña', models.IntegerField()),
                ('comentarios', models.CharField(max_length=100)),
            ],
        ),
    ]
