# Generated by Django 4.0.5 on 2022-08-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0013_valecreditelcdelacasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='valecreditelcdelacasa',
            name='num_cajera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valecreditelcdelacasa',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valecreditelcdelacasa',
            name='imp_facturado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valecreditelcdelacasa',
            name='num_dev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valecreditelcdelacasa',
            name='num_seña',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valecreditelcdelacasa',
            name='num_vta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valecreditelcdelacasa',
            name='usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
