# Generated by Django 4.0.5 on 2022-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajasApp', '0015_valecreditelcdelacasa_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('importe_cliente', models.IntegerField()),
                ('genero_cliente', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=20)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('num_cajera', models.IntegerField(blank=True, null=True)),
                ('num_vta', models.IntegerField(blank=True, null=True)),
                ('num_dev', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
