# Generated by Django 4.0.3 on 2022-07-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_cancelacioncliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiosML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('Fecha', models.DateField()),
                ('Nombre', models.CharField(max_length=50)),
                ('CI', models.IntegerField()),
                ('Pedido', models.IntegerField()),
                ('Fecha_compra', models.DateField()),
                ('Importe', models.IntegerField()),
                ('Comentario', models.TextField(max_length=200)),
            ],
        ),
    ]
