# Generated by Django 4.0.3 on 2022-07-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fun', models.CharField(max_length=30)),
                ('apellido_fun', models.CharField(max_length=30)),
                ('ci_fun', models.IntegerField()),
                ('numero_fun', models.IntegerField()),
                ('cargo_fun', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Encargado', 'Encargado'), ('Cajera', 'Cajera'), ('Administrativo', 'Administrativo'), ('Aux Ventas', 'Aux Ventas'), ('Aux Deposito', 'Aux Deposito')], max_length=30)),
                ('sexo_fun', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('estado_fun', models.CharField(choices=[('Activo', 'Activo'), ('Egreso', 'Egreso'), ('Seg_Paro', 'Seg_Paro'), ('Seg_Medico', 'Seg_Medico')], max_length=30)),
            ],
        ),
    ]
