# Generated by Django 4.0.3 on 2022-07-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuncionariosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='apellido_fun',
            new_name='apellido_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='cargo_fun',
            new_name='cargo_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='ci_fun',
            new_name='cedula_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='estado_fun',
            new_name='estado_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='nombre_fun',
            new_name='nombre_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='numero_fun',
            new_name='numero_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='sexo_fun',
            new_name='sexo_funcionario',
        ),
    ]
