# Generated by Django 4.0.3 on 2022-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncionariosApp', '0002_rename_apellido_fun_funcionarios_apellido_funcionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursales', models.CharField(max_length=3)),
            ],
        ),
    ]
