# Generated by Django 4.0.5 on 2022-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmConveniosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobranzasConvenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_cobro', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50)),
                ('fecha_corte', models.DateField()),
                ('num_empresa', models.IntegerField()),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('mes_resumen', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50)),
                ('imp_resumen', models.IntegerField()),
                ('imp_bonificacion', models.IntegerField(blank=True, null=True)),
                ('num_documento', models.IntegerField(blank=True, null=True)),
                ('imp_resguardo', models.IntegerField(blank=True, null=True)),
                ('imp_recargo', models.IntegerField(blank=True, null=True)),
                ('imp_cobrar', models.IntegerField()),
                ('medio_pago', models.CharField(choices=[('Itau', 'Itau'), ('Brou', 'Brou'), ('Santander', 'Santander'), ('Scotiabank', 'Scotiabank'), ('Cheque', 'Cheque'), ('Efectivo', 'Efectivo')], max_length=50)),
                ('sap_banco', models.IntegerField(blank=True, null=True)),
                ('sap_convenios', models.IntegerField(blank=True, null=True)),
                ('imp_pago', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CobranzasConv',
        ),
    ]
