# Generated by Django 4.0.5 on 2022-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmConveniosApp', '0002_cobranzasconvenios_delete_cobranzasconv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranzasconvenios',
            name='fecha_corte',
            field=models.CharField(max_length=50),
        ),
    ]
