# Generated by Django 4.0.5 on 2022-08-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmConveniosApp', '0003_alter_cobranzasconvenios_fecha_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranzasconvenios',
            name='imp_bonificacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cobranzasconvenios',
            name='imp_recargo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cobranzasconvenios',
            name='imp_resguardo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cobranzasconvenios',
            name='num_documento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
