# Generated by Django 4.0.5 on 2022-07-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pago', models.CharField(choices=[('Oca', 'Oca'), ('Visa', 'Visa'), ('Abitab', 'Abitab'), ('Maser', 'Maser'), ('Anda', 'Anda'), ('Ebrou', 'Ebrou'), ('PassCard', 'PassCard'), ('Creditel', 'Creditel'), ('Cabal', 'Cabal'), ('Banred', 'Banred'), ('Tarjeta D', 'Tarjeta D'), ('MercadoPago', 'MercadoPago'), ('Credito de la casa', 'Credito de la casa'), ('Amex', 'Amex')], max_length=50)),
            ],
        ),
    ]
