# Generated by Django 4.0.5 on 2022-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionApp', '0002_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoDevolucion', models.CharField(choices=[('Falta de Stock', 'Falta de Stock'), ('Se arrepintio', 'Se arrepintio'), ('Error (talle, cuotas, articulos', 'Error (talle, cuotas, articulos'), ('Otros', 'Otros')], max_length=50)),
            ],
        ),
    ]
