# Generated by Django 4.0.3 on 2022-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionApp', '0003_motivodev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivodev',
            name='motivoDevolucion',
            field=models.CharField(choices=[('Falta de Stock', 'Falta de Stock'), ('Se arrepintio', 'Se arrepintio'), ('Error (talle, cuotas, articulos', 'Error (talle, cuotas, articulos)'), ('Otros', 'Otros')], max_length=50),
        ),
    ]
