# Generated by Django 4.0.5 on 2022-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionApp', '0005_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='respuesta',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
