# Generated by Django 4.0.7 on 2022-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionApp', '0007_mensajes_fecha_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_creado',
            field=models.DateField(auto_now=True, verbose_name='Fecha_creado'),
        ),
    ]
