# Generated by Django 4.0.5 on 2022-08-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionApp', '0008_alter_mensajes_fecha_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_suc', models.IntegerField()),
                ('direccion_suc', models.CharField(max_length=90)),
            ],
        ),
    ]
