# Generated by Django 4.0.5 on 2022-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionApp', '0011_alter_sucursales_numero_suc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_promo', models.CharField(max_length=50)),
                ('valor_promo', models.CharField(max_length=50)),
                ('descripcion_promo', models.CharField(max_length=200)),
                ('imagen_promo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alcance_promo', models.CharField(max_length=200)),
                ('estado_promo', models.BooleanField(default=False)),
            ],
        ),
    ]
