# Generated by Django 4.0.3 on 2022-07-24 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoBolsas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido_bolsas', models.DateField(blank=True, null=True)),
                ('cantidad_bolsa_chica', models.IntegerField(blank=True, null=True)),
                ('cantidad_bolsa_media', models.IntegerField(blank=True, null=True)),
                ('cantidad_bolsa_grande', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido_diseno', models.DateField(blank=True, null=True)),
                ('cantidad_tarj_presentacion', models.IntegerField(blank=True, null=True)),
                ('cantidad_tarj_atencion', models.IntegerField(blank=True, null=True)),
                ('cantidad_talon_cambio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido_farmacia', models.DateField(blank=True, null=True)),
                ('cantidad_ibuprofeno', models.IntegerField(blank=True, null=True)),
                ('cantidad_leuco', models.IntegerField(blank=True, null=True)),
                ('cantidad_iodofon', models.IntegerField(blank=True, null=True)),
                ('cantidad_gasa', models.IntegerField(blank=True, null=True)),
                ('cantidad_disan', models.IntegerField(blank=True, null=True)),
                ('cantidad_curitas', models.IntegerField(blank=True, null=True)),
                ('cantidad_algodon', models.IntegerField(blank=True, null=True)),
                ('cantidad_alcohol_rectificado', models.IntegerField(blank=True, null=True)),
                ('cantidad_alcohol_gel', models.IntegerField(blank=True, null=True)),
                ('cantidad_agua_oxigenada', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido_limpieza', models.DateField(blank=True, null=True)),
                ('cantidad_plumero', models.IntegerField(blank=True, null=True)),
                ('cantidad_insecticida', models.IntegerField(blank=True, null=True)),
                ('cantidad_pulidor_cremoso', models.IntegerField(blank=True, null=True)),
                ('cantidad_perfumol', models.IntegerField(blank=True, null=True)),
                ('cantidad_ph', models.IntegerField(blank=True, null=True)),
                ('cantidad_panos_piso', models.IntegerField(blank=True, null=True)),
                ('cantidad_limpia_vidrio', models.IntegerField(blank=True, null=True)),
                ('cantidad_hipoclorito', models.IntegerField(blank=True, null=True)),
                ('cantidad_jabon_liq', models.IntegerField(blank=True, null=True)),
                ('cantidad_franela', models.IntegerField(blank=True, null=True)),
                ('cantidad_esponja', models.IntegerField(blank=True, null=True)),
                ('cantidad_detergente', models.IntegerField(blank=True, null=True)),
                ('cantidad_cera_roja', models.IntegerField(blank=True, null=True)),
                ('cantidad_cera_inc', models.IntegerField(blank=True, null=True)),
                ('cantidad_bolsas', models.IntegerField(blank=True, null=True)),
                ('cantidad_lustramueble', models.IntegerField(blank=True, null=True)),
                ('cantidad_des_ambiente', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoLuces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido_precios', models.DateField(blank=True, null=True)),
                ('cantidad_ar111', models.IntegerField(blank=True, null=True)),
                ('cantidad_dicroica_led', models.IntegerField(blank=True, null=True)),
                ('cantidad_emb', models.IntegerField(blank=True, null=True)),
                ('cantidad_lampara', models.IntegerField(blank=True, null=True)),
                ('cantidad_par30_fria', models.IntegerField(blank=True, null=True)),
                ('cantidad_par30_calida', models.IntegerField(blank=True, null=True)),
                ('cantidad_tacho', models.IntegerField(blank=True, null=True)),
                ('cantidad_tubo_led', models.IntegerField(blank=True, null=True)),
                ('cantidad_driver', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_descuento', models.IntegerField()),
                ('fecha_descuento', models.DateField()),
                ('nombre_descuento', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
