# Generated by Django 4.0.3 on 2022-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPapeleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido_papeleria', models.DateField(blank=True, null=True)),
                ('cantidad_lapiceras', models.IntegerField(blank=True, null=True)),
                ('cantidad_clips', models.IntegerField(blank=True, null=True)),
                ('cantidad_lapiz', models.IntegerField(blank=True, null=True)),
                ('cantidad_lapiceras_mostra', models.IntegerField(blank=True, null=True)),
                ('cantidad_cinta_fina1', models.IntegerField(blank=True, null=True)),
                ('cantidad_cinta_fina2', models.IntegerField(blank=True, null=True)),
                ('cantidad_cinta_anchaT', models.IntegerField(blank=True, null=True)),
                ('cantidad_cinta_impresa', models.IntegerField(blank=True, null=True)),
                ('cantidad_etiqueta_60x40', models.IntegerField(blank=True, null=True)),
                ('cantidad_marcador_perm_fino', models.IntegerField(blank=True, null=True)),
                ('cantidad_marcador_fluor', models.IntegerField(blank=True, null=True)),
                ('cantidad_medias', models.IntegerField(blank=True, null=True)),
                ('cantidad_grapas', models.IntegerField(blank=True, null=True)),
                ('cantidad_pilasAA', models.IntegerField(blank=True, null=True)),
                ('Pilas AAA', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pedidoluces',
            old_name='cantidad_dicroica_led',
            new_name='Dicroica led',
        ),
    ]
