# Generated by Django 4.0.3 on 2022-07-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0004_pedidopapeleria_banda elastica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoluces',
            old_name='Dicroica led',
            new_name='Dicroica_led',
        ),
        migrations.RenameField(
            model_name='pedidoluces',
            old_name='Par30 - calida',
            new_name='Par30_calida',
        ),
        migrations.RenameField(
            model_name='pedidoluces',
            old_name='Par30 - fria',
            new_name='Par30_fria',
        ),
        migrations.RenameField(
            model_name='pedidoluces',
            old_name='Tubo led',
            new_name='Tubo_led',
        ),
        migrations.RenameField(
            model_name='pedidoluces',
            old_name='Fecha pedido',
            new_name='fecha_pedido_luces',
        ),
    ]
