# Generated by Django 4.0.3 on 2022-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0006_rename_bolsa chica_pedidobolsas_bolsa_chica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoReparaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_servicio', models.CharField(blank=True, max_length=20, null=True)),
                ('asunto_reparacion', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario_reparacion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado_reparacion', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Resuelto', 'Resuelto')], max_length=20, null=True)),
                ('fecha_resuelto', models.DateField(blank=True, null=True)),
                ('comentarios_resuelto', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
