# Generated by Django 4.0.3 on 2022-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0007_pedidoreparaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoreparaciones',
            name='nombre_servicio',
            field=models.CharField(blank=True, choices=[('Aire acondicionado', 'Aire acondicionado'), ('Sanitario', 'Sanitario'), ('Electricidad', 'Electricidad'), ('Vidriero', 'Vidriero'), ('Albañileria', 'Albañileria')], max_length=20, null=True),
        ),
    ]
