# Generated by Django 4.0.3 on 2022-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0008_alter_pedidoreparaciones_nombre_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoreparaciones',
            old_name='asunto_reparacion',
            new_name='Asunto',
        ),
        migrations.RenameField(
            model_name='pedidoreparaciones',
            old_name='comentario_reparacion',
            new_name='Comentario',
        ),
        migrations.RenameField(
            model_name='pedidoreparaciones',
            old_name='comentarios_resuelto',
            new_name='Comentario_resuelto',
        ),
        migrations.RenameField(
            model_name='pedidoreparaciones',
            old_name='estado_reparacion',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='pedidoreparaciones',
            old_name='fecha_resuelto',
            new_name='Fecha_pedido',
        ),
        migrations.RenameField(
            model_name='pedidoreparaciones',
            old_name='nombre_servicio',
            new_name='Servicio',
        ),
        migrations.AddField(
            model_name='pedidoreparaciones',
            name='Fecha_resuelto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
