# Generated by Django 4.0.3 on 2022-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0009_rename_asunto_reparacion_pedidoreparaciones_asunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidobolsas',
            name='Fecha_pedido',
        ),
        migrations.AddField(
            model_name='descuentos',
            name='fecha_creado',
            field=models.DateField(auto_now=True, verbose_name='Fecha creado'),
        ),
        migrations.AddField(
            model_name='pedidobolsas',
            name='fecha_creado',
            field=models.DateField(auto_now=True, verbose_name='Fecha creado'),
        ),
    ]
