# Generated by Django 4.0.3 on 2022-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0010_remove_pedidobolsas_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidobolsas',
            name='fecha_creado',
        ),
        migrations.AddField(
            model_name='pedidobolsas',
            name='Fecha_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
