# Generated by Django 4.0.5 on 2022-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0014_alter_descuentos_fecha_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidobolsas',
            name='Fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodiseno',
            name='Fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidofarmacia',
            name='Fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidolimpieza',
            name='Fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoluces',
            name='Fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidopapeleria',
            name='Fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
