# Generated by Django 4.0.5 on 2022-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0015_pedidobolsas_fecha_enviado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('monedas_1', models.IntegerField()),
                ('monedas_2', models.IntegerField()),
                ('monedas_5', models.IntegerField()),
                ('monedas_10', models.IntegerField()),
                ('billetes_20', models.IntegerField()),
                ('billetes_50', models.IntegerField()),
                ('billetes_100', models.IntegerField()),
                ('billetes_200', models.IntegerField()),
            ],
        ),
    ]
