# Generated by Django 4.0.5 on 2022-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0019_pedidouniforme_fecha_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeConrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('fecha_vta', models.DateField()),
                ('num_vale', models.IntegerField()),
                ('nombre_fun', models.CharField(max_length=100)),
                ('num_vta', models.IntegerField()),
                ('num_dev', models.IntegerField()),
            ],
        ),
    ]
