# Generated by Django 4.0.5 on 2022-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0022_rename_fecha_pedido_valeapmu_fecha_carga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeUniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('ci_fun', models.IntegerField()),
                ('num_fun', models.IntegerField()),
                ('nombre_fun', models.CharField(max_length=60)),
                ('cargo_fun', models.CharField(max_length=60)),
                ('articulo', models.CharField(max_length=17)),
                ('comentario', models.CharField(max_length=150)),
                ('estado_autorizacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Resuelto', 'Resuelto')], max_length=10)),
                ('fecha_resolucion', models.DateField()),
                ('comentario_adm', models.CharField(max_length=500)),
                ('num_vta', models.IntegerField()),
            ],
        ),
    ]
