# Generated by Django 4.0.5 on 2022-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0024_rename_comentario_chequeuniforme_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeuniforme',
            name='comentario_adm',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chequeuniforme',
            name='estado_autorizacion',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Resuelto', 'Resuelto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chequeuniforme',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequeuniforme',
            name='num_vta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
