# Generated by Django 4.0.5 on 2022-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormulariosApp', '0025_alter_chequeuniforme_comentario_adm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeuniforme',
            name='estado_autorizacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, null=True),
        ),
    ]
