# Generated by Django 4.0.3 on 2022-07-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_luces', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('nombre_luces', models.CharField(max_length=20)),
            ],
        ),
    ]
