# Generated by Django 4.0.3 on 2022-07-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticulosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bolsas', models.CharField(max_length=20)),
                ('codigoSAP_bolsas', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_diseno', models.CharField(max_length=30)),
                ('codigoSAP_diseno', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_farmacia', models.CharField(max_length=30)),
                ('codigoSAP_farmacia', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Limpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_limpieza', models.CharField(max_length=30)),
                ('codigoSAP_limpieza', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papeleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_papeleria', models.CharField(max_length=30)),
                ('codigoSAP_papeleria', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='luces',
            name='codigoSAP_luces',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
