# Generated by Django 4.0.3 on 2022-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticulosApp', '0002_bolsas_diseno_farmacia_limpieza_papeleria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsas',
            name='medida_bolsas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diseno',
            name='medida_diseno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='medida_farmacia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='limpieza',
            name='medida_limpieza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='luces',
            name='medida_luces',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='papeleria',
            name='medida_papeleria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
