# Generated by Django 4.0.3 on 2022-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticulosApp', '0007_reparaciones_email_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparaciones',
            name='tel_contacto',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
