# Generated by Django 4.0.3 on 2022-07-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticulosApp', '0009_rename_email_contacto_reparaciones_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_noticia', models.CharField(max_length=50)),
                ('descripcion_noticia', models.CharField(max_length=200)),
                ('noticia_noticia', models.TextField(max_length=5000)),
                ('imagen_noticia', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('tema_noticia', models.CharField(choices=[('Pago Sueldos', 'Pago Sueldos'), ('Pago Aguinaldo', 'Pago Aguinaldo'), ('Beneficios Funcionarios', 'Beneficios Funcionarios'), ('Comunicado General', 'Comunicado General')], max_length=50)),
            ],
        ),
    ]
