# Generated by Django 4.0.3 on 2022-07-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticulosApp', '0010_noticias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='descripcion_noticia',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='imagen_noticia',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='nombre_noticia',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='noticia_noticia',
            new_name='Noticia',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='tema_noticia',
            new_name='Tema',
        ),
    ]
