# Generated by Django 4.0.3 on 2022-07-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticulosApp', '0011_rename_descripcion_noticia_noticias_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fecha_noticia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
